# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Duy Nguyen
title: Senior Network System Administrator
email: duy@berkeley.edu
website: dnguyenocc.github.io

# Social links
# linkedin_username: facespics
github_username:  dnguyenocc
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: dnguyenocc
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Duy. I am a quick-learner, and a software developer with experience in Python, Java, Ruby on Rails, Data Structures and Algorithms. Strong engineering professional with a Bachelor's degree focused in Computer Science from University of California, Berkeley.

  I enjoy solving complex problems and love working on a team and pair programming.

  I am always looking for more opportunities to dive into new programming languages, technologies, or mathematical concepts.
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Soccer
   - Hiking
   - Snorkeling

# Footer
footer_show_references: true

# Build settings
# remote_theme: sproogen/resume-themse

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
